### ISSUE TITLE
I'm getting an error "Cannot read property 'author' of undefined"

### ISSUE THREAD

**Issue by DoubleBullet** [MrZillaGold/discord.js-pages#107]
Hello,

I'm getting this error when trying to use the pagesbuilder. This is my first time using it and I have no idea why it's throwing me this error: 
`(node:8632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'author' of undefined`

Here is my code:
```
    const builder = new PagesBuilder(msg)
    .setTitle("Pages Test")
    .setAuthor("Bot")
    .addPages([new MessageEmbed()
                    .setDescription("Page One!"),
                new MessageEmbed()
                    .setDescription("Page Two!")
                ])
    .addField("Global field", "discord.js-pages", true)
    .setColor("GREEN");

    builder.build();
```

Originally I didn't set an author but still got the same error. Let me know if I'm doing anything wrong.

**Comment by MrZillaGold** [comment]
Hi! Can you send all error stack trace?

**Comment by DoubleBullet** [comment]
sure.

```
(node:8632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'author' of undefined
    at new PagesBuilder (Q:\GitHubRepositories\Miner_Bot\node_modules\discord.js-pages\lib\PagesBuilder.js:32:33)
    at Object.module.exports [as page] (Q:\GitHubRepositories\Miner_Bot\commands\page.js:9:21)
    at Client.module.exports (Q:\GitHubRepositories\Miner_Bot\commands.js:73:31)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (Q:\GitHubRepositories\Miner_Bot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (Q:\GitHubRepositories\Miner_Bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)  
    at WebSocketManager.handlePacket (Q:\GitHubRepositories\Miner_Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (Q:\GitHubRepositories\Miner_Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (Q:\GitHubRepositories\Miner_Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (Q:\GitHubRepositories\Miner_Bot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (Q:\GitHubRepositories\Miner_Bot\node_modules\ws\lib\websocket.js:970:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (Q:\GitHubRepositories\Miner_Bot\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (Q:\GitHubRepositories\Miner_Bot\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (Q:\GitHubRepositories\Miner_Bot\node_modules\ws\lib\receiver.js:143:22)
(node:8632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by MrZillaGold** [comment]
Try `1.3.0-rc.3` version

**Comment by MrZillaGold** [comment]
I'll check later today

**Comment by MrZillaGold** [comment]
I'm sorry for the wait.

In the examples, the construct is not correct to use, you must pass an object with the `message` field when initializing the class:
```js
client.on("message", (message) => {
    new PagesBuilder({ message })
        .setTitle("Global title")
        .setPages([
            new MessageEmbed()
                .setDescription("First page"),
            new MessageEmbed()
                .setDescription("Second page")
        ])
        .addField("Global field", "discord.js-pages", true)
        .setColor("GREEN")
        .build();
});
```

Also pay attention to the [`middleware example`](https://github.com/MrZillaGold/discord.js-pages/blob/master/docs/examples/middleware-example.js), it will also be useful for you
